name: Dashboard Deployment

on:
  push:
    branches:
      - main

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Set environment variable
        run: |
          echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_AUTH_API_URL=${{ secrets.NEXT_PUBLIC_AUTH_API_URL }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Copy .next build folder to server
        run: |
          scp -r .next ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/var/www/dashboard/

      - name: Finalize deployment on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /var/www/dashboard

            pm2 stop dashboard || true
            pm2 delete dashboard || true

            npm ci --production
            pm2 start npm --name "dashboard" -- start
            pm2 save

            sudo systemctl reload nginx
            akamai purge --url https://algoarena.co.in/* || echo "Akamai purge failed"

      - name: Verify deployment
        run: |
          sleep 10
          curl -f https://algoarena.co.in/ || exit 1
